config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  root to: 'jobs#index'

  resources :jobs, only: ["new", "create", "index", "destroy"] do
    resources :job_applications, only: ["new", "create", "index"]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  namespace :api do
    namespace :v1 do
      resources :jobs, only: ["index"]
    end
  end
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :category
  belongs_to :company
  has_many :job_applications, dependent: :destroy

  scope :by_category, -> (category) { joins(:category).where("categories.title = ?", category) }
  scope :for_term, -> (term) { joins(:company).where("lower(jobs.title) like ? or lower(companies.name) like ?", "%#{term.to_s.downcase}%", "%#{term.to_s.downcase}%") }
  scope :sorted_by_date ,-> { order(created_at: :desc) }
  scope :already_started, -> { where("jobs.start_date <= ?", Date.today) }

  include JobConcern
end

app/controllers/api/v1/jobs_controller.rb
require_relative '../../api/api_controller'

class Api::V1::JobsController < Api::ApiController

  def index
    render json: BrowseJobsQuery.new().browse_jobs(params)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[ destroy ]
  before_action :authenticate_user!, only: %i[ new create ]

  # GET /jobs or /jobs.json
  def index
    @jobs = BrowseJobsQuery.new().browse_jobs(params)
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # POST /jobs or /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        redirect_to jobs_path, notice: "Job was successfully created."
      else
        render json: @job.errors, status: :unprocessable_entity
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Job was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:title, :description, :start_date, :end_date, :category_id, :company_id)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def categories
    Category.all
  end

  def companies
    Company.all
  end

  def categories_for_select
    categories.map { |c| [c.title, c.id] }
  end

  def companies_for_select
    companies.map { |c| [c.name, c.id] }
  end

  def progress_tooltip_text(job)
    if job.expired?
      "Job posting expired " + pluralize(job.expired_ago, "day") + "  ago"
    else
      "Job posting opened " + pluralize(job.started_before, "day") + " ago, expires in " + pluralize(job.expires_in, "day")
    end
  end
end

app/views/jobs/_form.html.erb
<%= form_with(model: job) do |form| %>

  <div class="form-group row">
    <div class="col-3"><%= form.label :title %></div>
    <div class="col-9">
      <%= form.text_field :title, class: "form-control" %>
      <% unless job.errors.full_messages_for(:title).empty? %>

        <div class="col-9 text-danger small apply-form-error">
          <%= job.errors.full_messages_for(:title).first %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-3"><%= form.label :description %></div>
    <div class="col-9">
      <%= form.text_area :description, class: "form-control", rows: 6 %>
      <% unless job.errors.full_messages_for(:description).empty? %>

        <div class="col-9 text-danger small apply-form-error">
          <%= job.errors.full_messages_for(:description).first %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-3"><%= form.label :start_date %></div>
    <div class="col-9">
      <%= form.text_field :start_date, class: "form-control datepicker" %>
      <% unless job.errors.full_messages_for(:start_date).empty? %>

        <div class="col-9 text-danger small apply-form-error">
          <%= job.errors.full_messages_for(:start_date).first %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-3"><%= form.label :end_date %></div>
    <div class="col-9">
      <%= form.text_field :end_date, class: "form-control datepicker" %>
      <% unless job.errors.full_messages_for(:end_date).empty? %>

        <div class="col-9 text-danger small apply-form-error">
          <%= job.errors.full_messages_for(:end_date).first %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-3"><%= form.label :category_id, "Category" %></div>
    <div class="col-9">
      <%= form.select :category_id, categories_for_select, class: "form-control" %>
      <% unless job.errors.full_messages_for(:category_id).empty? %>

        <div class="col-9 text-danger small apply-form-error">
          <%= job.errors.full_messages_for(:category_id).first %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-3"><%= form.label :company_id, "Company" %></div>
    <div class="col-9">
      <%= form.select :company_id, companies_for_select, class: "form-control" %>
      <% unless job.errors.full_messages_for(:company_id).empty? %>

        <div class="col-9 text-danger small apply-form-error">
          <%= job.errors.full_messages_for(:company_id).first %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit "Add", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/jobs/_job_info.html.erb
<div class="card mb-5 mt-3 bg-light">
  <div class="card-header">
    You're applying for a position <%= job.title %> at <%= job.company.name %>
  </div>
  <div class="card-body">
    <h5 class="card-title">Job posted <%= pluralize(job.started_before, "day") %> ago. Expires
      in <%= pluralize(job.expires_in, "day") %></h5>
    <p class="card-text"><%= pluralize(job.job_applications.size, "person") %> already applied for this job</p>
  </div>
</div>

app/views/jobs/_job_item.html.erb
<% apply_btn_class = "btn btn-primary btn-sm small apply" %>
<% if job.expired? %>
  <% apply_btn_class += " disabled" %>
<% end %>

<div class="card bg-light mb-2 border-0 p-2 job-item">
  <div class="card-body">
    <div>
      <a class="text-dark text-decoration-none" data-toggle="collapse" role="button" href="#job<%= job.id %>" aria-expanded="false" aria-controls="job<%= job.id %>">
        <div class="row">
          <div>
            <h5 class="card-title">
              <%= job.company.name %>
            </h5>
          </div>
          <div class="pl-2">
            <span class="badge badge-dark"><%= job.category.title %></span>
          </div>
        </div>
      </a>
    </div>

    <div class="card border-0 bg-light collapse" id="job<%= job.id %>">
      <div class="row">
        <div class="pr-5">
          <i class="bi bi-mailbox pr-2"></i><a href="mailto:<%= job.company.email %>"><%= job.company.email %></a></div>
        <div class="pr-5"><i class="bi bi-calendar pr-2"></i><%= job.company.created_at %></div>
      </div>
    </div>

    <hr class="my-1">
    <div class="row">
      <div class="col pl-0">
        <div class="row pl-3 justify-content-start">
          <div>
            <p class="card-text lead"><%= job.title %></p>
          </div>
          <div>
            <% if job.expired? %>
              <span class="badge badge-danger ml-2">Expired</span>
            <% end %>
          </div>
        </div>

      </div>
      <div class="col-3">
        <div class="progress" data-toggle="tooltip" data-placement="top" title="<%= progress_tooltip_text(job) %>">
          <div class="progress-bar" role="progressbar" style="width: <%= job.progress_value_percentage %>%" aria-valuenow="<%= job.progress_value %>" aria-valuemin="0" aria-valuemax="<%= pluralize(job.duration, "days") %>"></div>
        </div>
      </div>
    </div>

    <div class="row">
      <p class="font-weight-light small"><%= job.description %></p>

    </div>

    <div class="row mt-2 btn-sm">
      <div class="col-6">
        <div class="row">
          <div>
            <a href="<%= new_job_job_application_path(job) %>" class="<%= apply_btn_class %>">Apply now</a>
          </div>
          <div class="pl-2">
            <a href="#" class="badge badge-info job-applications-count" data-toggle="tooltip" data-placement="right" title="<%= pluralize(job.job_applications.size, "person") %> applied to this job"><%= job.job_applications.size %></a>
          </div>
        </div>
      </div>
      <% if user_signed_in? %>
        <div class="float-right ml-auto">
          <%= link_to "Applications", job_job_applications_path(job), class: "btn btn-sm btn-success" %>
          <%= link_to "Remove job", job_path(job), method: "delete", class: "btn btn-sm btn-danger", data: { confirm: "Are you sure you want to remove job #{job.title} at #{job.company.name}" } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/jobs/index.html.erb
<div class="container jobs">
  <div class="jumbotron pb-2 pt-5 mt-3 mb-3">
    <h1 class="display-5">Find the job you dream about !</h1>
    <p class="lead">The most extensive list of jobs on the market. Get in contact with employee in minimum amount of time</p>
  </div>

  <% flash.each do |type, message| %>
    <div class="alert alert-success" role="alert">
      <%= message %>
    </div>
  <% end %>

  <% if @jobs.empty? %>
    <p class="text-secondary">No jobs for this criteria. Please broaden your search</p>
  <% else %>
    <% @jobs.each do |job| %>
      <%= render "job_item", job: job %>
    <% end %>
  <% end %>
</div>

app/views/jobs/new.html.erb
<div class="container mt-5">
  <%= render 'form', job: @job %>
</div>