config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  root to: 'jobs#index'

  resources :jobs, only: ["new", "create", "index", "destroy"] do
    resources :job_applications, only: ["new", "create", "index"]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  namespace :api do
    namespace :v1 do
      resources :jobs, only: ["index"]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobsAndMore</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.0.4/popper.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
  <link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.1/css/datepicker.css" rel="stylesheet"/>

  <script type='text/javascript'>
      $(document).ready(function () {


          const endDate = new Date();
          endDate.setFullYear(endDate.getFullYear() - 18);
          const endDateStr = endDate.getFullYear() + "-" + (endDate.getMonth() + 1) + "-" + endDate.getDate();

          console.log(`xxx endDateStr: ${endDateStr}`);
          $('#job_application_birth_date').datepicker({ format: 'yyyy-mm-dd', autoclose: true, startDate: '1920-01-01', endDate: endDateStr });

          const startDate = new Date();
          const startDateStr = startDate.getFullYear() + "-" + (startDate.getMonth() + 1) + "-" + startDate.getDate();

          $('#job_start_date').datepicker({ format: 'yyyy-mm-dd', autoclose: true, startDate: startDateStr });

          $('#job_end_date').datepicker({ format: 'yyyy-mm-dd', autoclose: true });

      });
  </script>
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= jobs_path %>">Jobs</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Category
        </a>

        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% categories.each do |category| %>
            <%= link_to category.title, jobs_path(@current_params.merge(category: category.title)), class: "dropdown-item" %>
          <% end %>
          <%= link_to "All", jobs_path, class: "dropdown-item" %>

        </div>
      </li>

      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Add new job", new_job_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
      </li>
    </ul>

    <%= form_with url: jobs_path, method: :get, class: "form-inline my-2 my-lg-0" do |form| %>
      <% unless @current_params[:category].nil? %>
        <%= form.hidden_field :category, value: @current_params[:category] %>
      <% end %>
      <%= form.text_field :term, class: "form-control mr-sm-2", type: "search", placeholder: "Search" %>
    <% end %>
  </div>
</nav>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/no_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobsAndMore</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.0.4/popper.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
  <link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.1/css/datepicker.css" rel="stylesheet"/>
</head>

<body>

<% unless alert.nil? %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<% unless notice.nil? %>
  <p class="alert alert-success"><%= notice %></p>
<% end  %>

<div class="container">
<%= yield %>
</div>

</body>
</html>